ExcelRead/ExcelRead/Models/ErrorViewModel.cs
using System;

namespace ExcelRead.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExcelRead/ExcelRead/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExcelRead.Models
{
    public class Product
    {
        public int idProduct { get; set; }
        public string Title { get; set; }
        public string UrlImage { get; set; }
        public string Detail { get; set; }
        public int Price { get; set; }

    }
}

ExcelRead/ExcelRead/Controllers/ExcelController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ExcelDataReader;
using ExcelRead.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ExcelRead.Controllers
{
    public class ExcelController : Controller
    {
        private readonly IHostingEnvironment _appEnvironment;

        public ExcelController(IHostingEnvironment appEnvironment)
        {
            this._appEnvironment = appEnvironment;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(IFormCollection collection)
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                List<Product> products = new List<Product>();
                foreach (var item in files)
                {
                    if (item.Length > 0 && item != null)
                    {
                        string file_name = Guid.NewGuid().ToString().Replace("-", "") + "_" + item.FileName;
                        string uploads = Path.Combine(_appEnvironment.WebRootPath, "files");
                        string urlPart = uploads + "/" + file_name;
                        string extension = Path.GetExtension(urlPart);
                        if (extension == ".xls" || extension == ".xslx")
                        {
                            using (var fileStream = new FileStream(Path.Combine(uploads, file_name), FileMode.Create))
                            {
                                await item.CopyToAsync(fileStream);
                            }
                            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
                            using (var stream = System.IO.File.Open(urlPart, FileMode.Open, FileAccess.Read))
                            {
                                using (var reader = ExcelReaderFactory.CreateReader(stream))
                                {
                                    do
                                    {
                                        if (reader.Name == "page1" || reader.Name == "page2")
                                        {
                                            while (reader.Read())
                                            {
                                                products.Add(new Product
                                                {
                                                    idProduct = int.Parse(reader.GetValue(0).ToString()),
                                                    Title = reader.GetValue(1).ToString(),
                                                    UrlImage = reader.GetValue(2).ToString(),
                                                    Price = int.Parse(reader.GetValue(3).ToString()),
                                                    Detail = reader.GetValue(4).ToString()
                                                });
                                            }
                                        }
                                    } while (reader.NextResult());
                                }

                            }

                        }

                    }
                }
                if (products.Count > 0)
                {
                    //return Json(products);
                    ViewBag.products = products;
                    return View();
                }
                return RedirectToAction(nameof(Index));

            }
            return RedirectToAction(nameof(Index));
        }

    }
}

ExcelRead/ExcelRead/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ExcelRead.Models;

namespace ExcelRead.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExcelRead/ExcelRead/Views/Excel/Index.cshtml
@model IEnumerable<Product>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-8">
        <h2>Read file</h2>
        <form asp-controller="Excel" asp-action="Index" enctype="multipart/form-data">
            @Html.AntiForgeryToken()
            <div class="form-group">
                <label>Choose excel file</label>
                <input type="file" name="file" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" name="submit" value="Upload" />
            </div>
        </form>
    </div>
    <div class="col-md-8">
        @if (ViewBag.products != null)
        {
            <table class="table">
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>UrlImage</th>
                    <th>Price</th>
                    <th>Detail</th>
                </tr>
                @foreach (var item in ViewBag.products)
                {
                    <tr>
                        <td>@item.idProduct</td>
                        <td>@item.Title</td>
                        <td>@item.UrlImage</td>
                        <td>@item.Price</td>
                        <td>@item.Detail</td>
                    </tr>
                }
            </table>
        }
    </div>
</div>

ExcelRead/ExcelRead/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ExcelRead/ExcelRead/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExcelRead</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExcelRead</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ExcelRead - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>